### ISSUE TITLE
ICSP Error when adding a server

### ISSUE THREAD

**Issue by ollypom** [HewlettPackard/docker-machine-oneview#94] opened 2016-08-22 16:11 UTC
Hey, when running the docker-machine create command i get a Status 500 from ICSP. Looking at Debug i see the following. 

```
(swarm-node-04) DBG | RestAPICall POST - https://icsp.test.local/rest/os-deployment-servers
(swarm-node-04) DBG | *** url => https://icsp.test.local/rest/os-deployment-servers
(swarm-node-04) DBG | *** method => 
(swarm-node-04) DBG | *** options => {"port":443,"username":"Administrator","password":"password"}
(swarm-node-04) DBG | Headers -> auth -> KkaOdY4fJlX1n21asQk9KiVFEbA3Jkor
(swarm-node-04) DBG | 
(swarm-node-04) DBG | Headers -> Content-Type -> application/json; charset=utf-8
(swarm-node-04) DBG | 
(swarm-node-04) DBG | Headers -> X-API-Version -> 108
(swarm-node-04) DBG | 
(swarm-node-04) DBG | REQ    --> &{Method:POST URL:https://icsp.test.local/rest/os-deployment-servers Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Content-Type:[application/json; charset=utf-8] X-Api-Version:[108] Auth:[KkaOdY4fJlX1n21asQk9KiVFEbA3Jkor]] Body:{Reader:} ContentLength:61 TransferEncoding:[] Close:false Host:icsp.twlon.com Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr: RequestURI: TLS:<nil> Cancel:<nil>}
(swarm-node-04) DBG | 
(swarm-node-04) DBG | RESP   --> &{Status:500 Server Error StatusCode:500 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Cache-Control:[no-cache] Date:[Mon, 22 Aug 2016 15:00:49 GMT] Content-Type:[application/json;charset=UTF-8] Via:[1.1 icsp.test.local] Vary:[Accept-Encoding]] Body:0xc8201ed640 ContentLength:-1 TransferEncoding:[chunked] Close:true Trailer:map[] Request:0xc82014e380 TLS:0xc8203926e0}
```

i think this is because it is not passing the IP address of the iLO to ICSP. Looking higher up the output i see. 

(`swarm-node-04) DBG | GetCurrentPowerState() blade -> {ServerHardwarev200:{IntelligentProvisioningVersion:2.20.219 MpHostInfo:0xc8204a1d10 MpState:OK PortMap:0xc8204f7f60 ServerSettings:0xc820510e80 Signature:0xc820510ea0} AssetTag:[Unknown] Category:server-hardware Created:2016-03-15T10:05:25.671Z Description: ETAG:1471803258698 FormFactor:HalfHeight LicensingIntent:OneView LocationURI:/rest/enclosures/09CZ35293RS1 MemoryMb:163840 Model:ProLiant BL460c Gen9 Modified:2016-08-21T18:14:18.698Z MpFirwareVersion:2.40 Dec 02 2015 MpModel:iLO4 Name:C7000-Rack8, bay 5 PartNumber:727021-B21 Position:5 PowerLock:false PowerState:Off ProcessorCoreCount:6 ProcessorCount:2 ProcessorSpeedMhz:1900 ProcessorType:Intel(R) Xeon(R) CPU E5-2609 v3 @ 1.90GHz RefreshState:NotRefreshing RomVersion:I36 12/28/2015 SerialNumber:CZ35210RS3 ServerGroupURI:/rest/enclosure-groups/8aa07098-ece1-4568-ae9a-bbf9fcde48c9 ServerHardwareTypeURI:/rest/server-hardware-types/B40A6425-B4D2-4467-99BB-059263311F2E ServerProfileURI:/rest/server-profiles/eea9e3f9-6821-4f12-8ee5-66ff1eb5f5aa ShortModel:BL460c Gen9 State:ProfileApplied StateReason:NotApplicable Status:OK Type:server-hardware-4 URI:/rest/server-hardware/30373237-3132-5A43-3335-323933525333 UUID:30373237-3132-5A43-3335-323933525333 VirtualSerialNumber:VCGND6V04K VirtualUUID:eea9e3f9-6821-4f12-8ee5-66ff1eb5f5aa MpDnsName: MpIpAddress: Client:%!v(PANIC=runtime error: index out of range)}`

The bit of interest there is MpIpAddress: Client:%!v(PANIC=runtime error: index out of range)}. 

If it helps i am running OV version  2.00.07-0250853, and ICSP version 7.5.0-0209204, Aug 3, 2015.

Does anybody know why? Is it API versions?

**Comment by SweBarre** [comment] 2016-08-23 11:38
I see this aswell,
my config is: 
OV Version:  2.00.07-0250853 
ICSP Version: 7.5.1-0243931
docker-machine-driver-oneview version: 0.5.5
docker-machine version: 0.8.1, build 41b3b25

**Comment by wenlock** [comment] 2016-08-23 21:18
Hey, Trying to reproduce the issue with those versions, to see if it's something obvious.  Just to confirm on the iLo IP, that is something we calculate from the server profile.   I do have some questions on that.

* Was the server profile in OneView created for the server before hand or by the driver?
* When you navigate to server hardware that was assigned by the server profile, you should find a section called iLO.  Do you see a hostname and IPv4 address listed for the server?
* Is the IPv6 field empty with none, or is it populated?

Thanks for the additional information.   Also, if you can share the command line you tried for docker-machine create, that would be good as well.

**Comment by ollypom** [comment] 2016-08-23 21:43
Hey,

1) The profile is already defined in OV and the driver is copying and applying it to some hardware (On that point, even though I set the API version as 200 in my environment, it is unable to find a "Server Profile Template". The Profile specified in the command has to be a "Server Profile", maybe related).

2) Yes i see the hostname and ipv4 address in OV. ipv6 address is none.

3) I source these variables:

```
export ONEVIEW_APIVERSION=200

export ONEVIEW_ILO_USER=Administrator
export ONEVIEW_ILO_PASSWORD=password

export ONEVIEW_ICSP_ENDPOINT=https://icsp.test.local
export ONEVIEW_ICSP_USER=Administrator
export ONEVIEW_ICSP_PASSWORD=password
export ONEVIEW_ICSP_DOMAIN=LOCAL

export ONEVIEW_OV_ENDPOINT=https://oneview.test.local
export ONEVIEW_OV_USER=Administrator
export ONEVIEW_OV_PASSWORD=password
export ONEVIEW_OV_DOMAIN=LOCAL

export ONEVIEW_SSLVERIFY=false
```

and then run this command

```
docker-machine --debug create \
    --driver oneview \
    --oneview-server-template "machine" \
    --oneview-os-plan "docker_centos" \
    --swarm \
    --swarm-discovery token://0f3c80f666c7a1fc4131e9a1298c5260 \
    swarm-node-04
```

Thanks a lot for your help :)

**Comment by wenlock** [comment] 2016-08-23 23:04
Ahh, ok, so here is another possibility for the issue, you should try to define the option:

`--oneview-public-connection-name`

The value for this should be equal to the value of the name given in the profile for the Connection which will be accessible to the system running docker-machine, so that commands like ssh will work to that particular connection.   This is also the interface that needs to get an automatic DHCP address for the network it comes online for.

I think it's possible that this connection might not exist because the default for the driver is to look for the 2nd interface and try to communicate with it as the public interface.   Do you know if you only have a single interface or connection?

**Comment by wenlock** [comment] 2016-08-23 23:07
![image](https://cloud.githubusercontent.com/assets/1907138/17912915/9a57dd34-694b-11e6-8987-ff6ed0ee729c.png)

In this case my option would be `--oneview-public-connection-name "LR0_A"`

**Comment by SweBarre** [comment] 2016-08-24 07:48
Hi,
I noticed that when I do a rest call to /rest/server-hardware/{id} with X-Api-Version:200 I get **mpIpAddresses** as a array,
the same call uing X-Api-Version:120 I do see **mpIpAddress** as a string.
Don't know If this has something to do with anything.

enyhow, here's my env

```
ONEVIEW_APIVERSION=200
ONEVIEW_ICSP_DOMAIN=LOCAL
ONEVIEW_ICSP_ENDPOINT=https://icsp.demo.hp.se
ONEVIEW_ICSP_PASSWORD=password
ONEVIEW_ICSP_USER=docker
ONEVIEW_ILO_DOMAIN=LOCAL
ONEVIEW_ILO_PASSWORD=password
ONEVIEW_ILO_USER=docker
ONEVIEW_OS_PLAN=Docker_OS
ONEVIEW_OV_DOMAIN=LOCAL
ONEVIEW_OV_ENDPOINT=https://oneview110.demo.hp.se
ONEVIEW_OV_PASSWORD=password
ONEVIEW_OV_USER=docker
ONEVIEW_SERVER_TEMPLATE=Docker_Template
ONEVIEW_SSLVERIFY=true

```

and I ran this command:
```
docker-machine --debug create --driver oneview --oneview-public-connection-name "PublicNet1" docker-node-01 2>&1 | tee output.txt
```
Attached you have the complete output.
[output.txt](https://github.com/HewlettPackard/docker-machine-oneview/files/434228/output.txt)

I've also tried with docker-machine-driver-oneview version v0.8.0-rc1 and a build from the current master, no luck with those either....


Cheers

**Comment by ollypom** [comment] 2016-08-24 12:47
I have just spun up a OneView 2.00.02 environment and tested my configurations and commands against that and it worked. The driver was able to read  Server Profile Templates and the iLO Address. I guess this is because OV 2.00.02 is using API Version 200 where as the OV2.00.07 is using API Version 201 :(

**Comment by wenlock** [comment] 2016-08-24 14:57
@ollypom awesome cool find, im hoping to be able to repro that this week and see if we can do a fix.

**Comment by wenlock** [comment] 2016-08-25 00:53
@ollypom I think i found a workaround to the api issue we're having during icsp login.  At least thats whats showing up for me.  I'm wondering if you could give it a try.

I'll work on a fix to avoid having to do this, but here is the workaround:

1. Login to ICsp as a system admin
2. Go to Settings, and edit the Security option.
3. Disable license acknowledgment requirement
![image](https://cloud.githubusercontent.com/assets/1907138/17952934/8b655260-6a23-11e6-8b87-99ef88445097.png)


Please let me know if that doesn't remove the issue your running into.

Thanks!

**Comment by ollypom** [comment] 2016-08-25 15:57
@wenlock I don't seem to have that tick box on my ICSP 7.5.0, i will upgrade to 7.5.1 now :(

**Comment by wenlock** [comment] 2016-09-06 01:23
@ollypom since you mentioned you don't have this dialog, I kept looking...  I think I know have a fix for this issue in https://github.com/HewlettPackard/oneview-golang/pull/75 

This problems is caused by an issue with detecting the correct api version to use when connecting to new versions of OneView.  I'm doing some testing on this and will cut pre-release binaries when my test work.  Stay tuned.  Thanks!

**Comment by wenlock** [comment] 2016-09-13 21:42
@ollypom could you give it another shot with this new binary:

https://github.com/HewlettPackard/docker-machine-oneview/releases/tag/v0.8.1

**Comment by ollypom** [comment] 2016-09-14 19:31
@wenlock I have just given that new binary a go and it worked :) I was able to deploy from a server profile template and the server was added to ICSP successfully. My versions OV 2.0.0.7 and ICSP 7.5.1. 

Am i still exporting x-api-version 200 or should i be exporting 201?

Thanks a lot :)

**Comment by wenlock** [comment] 2016-09-16 18:21
@ollypom sorry for delayed response, yes, you should be able to leave off the export setting for api versions.

**Comment by SweBarre** [comment] 2016-09-19 07:29
v0.8.1 works like a charm, thanks @wenlock

**Closed** 2016-09-26 15:43 UTC
